services:
  app:
    env_file:
      - .env
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    depends_on:
      - db

  db:
    image: mysql:8
    expose:
      - '3306'
    # ports:
    #   - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
